### ISSUE TITLE
CommentIcons are not shown correctly for all questions

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/s-forms-components#3] opened 2021-11-24 00:20 UTC
- Layout still not working correctly for "Vlastnik"
- no comment icon on Cena 
- no comment icon on "Ma provozovatele"
- no comment icon on Sekce s identifikatorem
- comment icon dialog is visualizing outside of the screen

![image](https://user-images.githubusercontent.com/3962237/143148951-070157e7-2644-4734-9ad9-d3036eec4573.png)

![image](https://user-images.githubusercontent.com/3962237/143148673-79fc01a6-47a7-4400-bcaf-6c0cbb6fc31d.png)

**Comment by LaChope** [comment] 2021-11-24 08:47
@blcham I think not everything was merged. I cannot reproduce most of the issues.

![image](https://user-images.githubusercontent.com/57750426/143204110-09f0af1c-7487-41c9-825e-a67d7dcbf456.png)

![image](https://user-images.githubusercontent.com/57750426/143204651-ee102f57-32f0-4041-ba16-4a5b12dec9e5.png)


What still needs to be done:

- [x] no comment icon on "Ma provozovatele"

**Closed as completed** 2021-11-25 10:18 UTC
